version: '3.1'

services:
    hacka_node:
        build: ../server
        ports:
            - 80:8080
        links:
            - hacka_mysql
        networks:
            hacka-network:
                ipv4_address: 172.16.0.2

    hacka_mysql:
        build: ./mysql
        volumes:
            - hacka_db:/var/lib/mysql:rw
        ports:
            - 3306:3306
        environment:
            # On development progress, database server will has no password.
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            # If needed, uncomment next line and append new appropriate password.
            # MYSQL_ROOT_PASSWORD: SAMPLE
        networks:
            hacka-network:
                ipv4_address: 172.16.0.3

volumes:
    hacka_db:

networks:
  hacka-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16