# Members Mocking Data
insert into Members (name, phone, email, github, groupname) values ('Verge', '01056267283', 'vdeedes0@yandex.ru', 'vtubb0', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Lelia', '01032390056', 'lboice1@goo.ne.jp', 'lacomb1', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Keary', '01001954598', 'knester2@list-manage.com', 'kferraro2', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Quintilla', '01085044221', 'qsibun3@devhub.com', 'qyork3', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Valdemar', '01034930822', 'vtackle4@liveinternet.ru', 'vbartrum4', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Thorin', '01001278266', 'tmacgruer5@clickbank.net', 'tlias5', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Jerrome', '01051925559', 'jmcdell6@51.la', 'jcausbey6', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Eloisa', '01072016509', 'esimeone7@acquirethisname.com', 'evaudrey7', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Leone', '01042908905', 'lchang8@fotki.com', 'lquerree8', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Job', '01022082085', 'jwadge9@bloomberg.com', 'jspino9', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Tull', '01063884655', 'talsinaa@yandex.ru', 'tlemoucheuxa', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Ed', '01075981469', 'etunsleyb@hao123.com', 'ecastelb', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Gweneth', '01094157249', 'gmaidesc@paypal.com', 'gheadlyc', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Bidget', '01071422406', 'bduggaryd@studiopress.com', 'bivanchovd', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Basilio', '01054773916', 'bcomettoie@tuttocitta.it', 'bstrathee', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Keeley', '01036351101', 'kniesingf@scientificamerican.com', 'kolorenshawf', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Jereme', '01077362012', 'jendleyg@tuttocitta.it', 'jcaulderg', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Galen', '01031863588', 'ghaycockh@google.pl', 'ghaggidonh', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Eleen', '01095088483', 'egillani@tripadvisor.com', 'ehemberyi', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Hugh', '01042581707', 'hkernerj@patch.com', 'hmccolmj', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Temp', '01044351555', 'tgaberk@cbc.ca', 'ttrittamk', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Felicle', '01003685957', 'fyurasovl@jigsy.com', 'felstonl', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Vladamir', '01087380953', 'vcollinettem@springer.com', 'vblenkhornm', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Hedda', '01058067482', 'hpoorn@europa.eu', 'hcorkishn', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Loria', '01014894373', 'lscholcrofto@ftc.gov', 'lgimenezo', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Nat', '01021327226', 'nshillaberp@qq.com', 'nhembryp', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Darice', '01090730014', 'dbinfordq@abc.net.au', 'dphilpaultq', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Wrennie', '01041149555', 'wivinsr@jigsy.com', 'wbateyr', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Vannie', '01004044152', 'vrawkesbys@princeton.edu', 'vcrowches', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Skell', '01022303210', 'sferraresit@eventbrite.com', 'ssanphert', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Meta', '01062828335', 'mlaurandu@smugmug.com', 'mmccliffertyu', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Kiah', '01003363195', 'kkeuningv@behance.net', 'kwardesworthv', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Fraser', '01050451253', 'ffroodw@psu.edu', 'fsherrumw', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Waneta', '01001102490', 'wbuckneyx@dell.com', 'wdytonx', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Merwin', '01077193337', 'mdimitriadesy@ifeng.com', 'mbelleey', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Betta', '01085794912', 'bsimkovitzz@smugmug.com', 'blimprechtz', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Cristi', '01025600176', 'ctunesi10@latimes.com', 'choopper10', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Terrye', '01013201261', 'tswalough11@mapy.cz', 'tply11', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Christoper', '01004908511', 'ctipton12@blogspot.com', 'cfairhall12', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Devon', '01069309713', 'ddrewitt13@lycos.com', 'dpalke13', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Mic', '01040708879', 'mjohnes14@google.com.au', 'mmawer14', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Carlynn', '01054994506', 'cmcquirter15@sbwire.com', 'ccorkitt15', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Vonnie', '01038031502', 'vprator16@biblegateway.com', 'vscrowton16', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Sutton', '01095150165', 'slaurencot17@tmall.com', 'sphiller17', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Kirby', '01047352091', 'kteulier18@cafepress.com', 'kshave18', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Kaitlin', '01069041783', 'kyoung19@blogger.com', 'kbartusek19', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Lethia', '01018853485', 'lkubicki1a@cam.ac.uk', 'lrevitt1a', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Killy', '01032272129', 'kmasselin1b@yahoo.co.jp', 'kjedrzejkiewicz1b', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Constantino', '01001989893', 'cmaywood1c@free.fr', 'cbyram1c', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Kettie', '01029087419', 'kwittey1d@bravesites.com', 'ktravers1d', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Rivi', '01049837829', 'rgunningham1e@netscape.com', 'rsailer1e', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Jobey', '01083299341', 'jhandaside1f@answers.com', 'jbigrigg1f', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Addison', '01081344257', 'abedome1g@chron.com', 'atoombes1g', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Vinson', '01060160783', 'vcalltone1h@wunderground.com', 'vbaylay1h', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Cassey', '01015489861', 'ccamous1i@spiegel.de', 'crogier1i', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Abra', '01057614274', 'amarchington1j@upenn.edu', 'aogelbe1j', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Willi', '01052751123', 'wbrandom1k@nyu.edu', 'wrossetti1k', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Wenda', '01051815729', 'worudden1l@xinhuanet.com', 'wsallter1l', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Charlot', '01044781386', 'cdurran1m@amazon.com', 'cruslinge1m', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Desiri', '01003226995', 'dsoggee1n@nydailynews.com', 'dgoulthorp1n', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Tessie', '01001830124', 'takhurst1o@techcrunch.com', 'tcrehan1o', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Loleta', '01033011831', 'lkagan1p@jigsy.com', 'lpartridge1p', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Marcus', '01061649627', 'mglassman1q@fotki.com', 'mjorden1q', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Michel', '01018219433', 'mmadigan1r@ow.ly', 'mcharnley1r', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Richmond', '01021634936', 'rvasilic1s@google.cn', 'rbanaszczyk1s', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Gail', '01066278960', 'gkedslie1t@quantcast.com', 'gnapthine1t', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Abba', '01080214067', 'afruchon1u@bravesites.com', 'apigdon1u', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Yorgos', '01057615342', 'ydeaves1v@ox.ac.uk', 'yridgedell1v', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Bogey', '01017753879', 'bbielfeldt1w@spiegel.de', 'bskayman1w', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Hester', '01069979329', 'hrouge1x@dedecms.com', 'hwharf1x', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Gabby', '01084558332', 'gdewerson1y@loc.gov', 'gsheilds1y', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Rodie', '01049277547', 'rbeentjes1z@parallels.com', 'rpedlingham1z', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Amby', '01010625397', 'anolot20@virginia.edu', 'abrahan20', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Shae', '01021791443', 'sadamides21@chron.com', 'sboothebie21', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Harrie', '01036897174', 'hblackburne22@si.edu', 'hcuruclis22', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Donica', '01004342489', 'dhowsan23@apple.com', 'dfenimore23', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Kile', '01058244127', 'klippett24@yale.edu', 'kjepensen24', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Michael', '01086562054', 'mparagreen25@macromedia.com', 'mcamus25', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Maren', '01050884716', 'mgold26@stanford.edu', 'mdarleston26', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Corbet', '01087024474', 'cfardell27@creativecommons.org', 'ckocher27', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Nicol', '01064694563', 'nreasce28@symantec.com', 'nrathke28', 'Daily');
insert into Members (name, phone, email, github, groupname) values ('Reginauld', '01070148448', 'rgrelik29@google.ru', 'rwyleman29', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Allyce', '01096911410', 'aborgnet2a@google.it', 'amatusevich2a', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Barbey', '01035371321', 'bffoulkes2b@scientificamerican.com', 'bshurrock2b', 'Yearly');
insert into Members (name, phone, email, github, groupname) values ('Clarine', '01034423040', 'cmedgewick2c@lulu.com', 'cwhile2c', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Susan', '01090078614', 'sepelett2d@miitbeian.gov.cn', 'sduchatel2d', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Arlinda', '01072320876', 'aphilipard2e@ed.gov', 'amewe2e', 'Weekly');
insert into Members (name, phone, email, github, groupname) values ('Dewey', '01026381224', 'dpratten2f@abc.net.au', 'dreed2f', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Flora', '01012742749', 'fshakspeare2g@walmart.com', 'fhansom2g', 'Never');
insert into Members (name, phone, email, github, groupname) values ('Pierrette', '01072726635', 'pbenesevich2h@youku.com', 'pherkess2h', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Broddy', '01090271418', 'bvyel2i@360.cn', 'bszymanek2i', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Jared', '01068545978', 'jmulles2j@ehow.com', 'jvanelli2j', 'Monthly');
insert into Members (name, phone, email, github, groupname) values ('Josepha', '01015775461', 'jcallway2k@gravatar.com', 'jhovenden2k', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Jessalin', '01045001417', 'jyuranovev2l@dion.ne.jp', 'jsagerson2l', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Annamarie', '01037833086', 'ablackall2m@jiathis.com', 'aharner2m', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Carny', '01047576852', 'crembaud2n@slideshare.net', 'cklauber2n', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Owen', '01077458452', 'owherton2o@quantcast.com', 'ohabin2o', 'Once');
insert into Members (name, phone, email, github, groupname) values ('Allayne', '01099314670', 'arendall2p@wisc.edu', 'acoughan2p', 'Often');
insert into Members (name, phone, email, github, groupname) values ('Lancelot', '01061312424', 'lmacrury2q@squidoo.com', 'locooney2q', 'Seldom');
insert into Members (name, phone, email, github, groupname) values ('Harry', '01022589685', 'hpersitt2r@usatoday.com', 'hkunisch2r', 'Weekly');

# Teams Mocking Data
insert into Teams (name, members, repos) values ('Never', '9,0,7', '저장소 이름 1');
insert into Teams (name, members, repos) values ('Once', '4,1,2', '저장소 이름 2');
insert into Teams (name, members, repos) values ('Seldom', '3,2,2', '저장소 이름 3');
insert into Teams (name, members, repos) values ('Often', '8,2,2', '저장소 이름 4');
insert into Teams (name, members, repos) values ('Daily', '2,3,0', '저장소 이름 5');
insert into Teams (name, members, repos) values ('Weekly', '7,4,4', '저장소 이름 6');
insert into Teams (name, members, repos) values ('Monthly', '4,3,7', '저장소 이름 7');
insert into Teams (name, members, repos) values ('Yearly', '4,0,9', '저장소 이름 8');

# Repository
insert into Repositories (username, reponame, commits) values ('user1', '저장소 이름 1', 0);
insert into Repositories (username, reponame, commits) values ('user2', '저장소 이름 2', 0);
insert into Repositories (username, reponame, commits) values ('user3', '저장소 이름 3', 0);
insert into Repositories (username, reponame, commits) values ('user4', '저장소 이름 4', 0);
insert into Repositories (username, reponame, commits) values ('user5', '저장소 이름 5', 0);
insert into Repositories (username, reponame, commits) values ('user6', '저장소 이름 6', 0);
insert into Repositories (username, reponame, commits) values ('user7', '저장소 이름 7', 0);
insert into Repositories (username, reponame, commits) values ('user8', '저장소 이름 8', 0);